AAP-35593
ansible/dvcs-action pull request #8
Opened 2024-11-28 17:42 UTC by jay-steurer

Recreating the [PR](https://github.com/ansible/dvcs-action/pull/3) 

* Renaming Branch to AAP-35593
* Adding unit tests to dvcs checks

2024-12-03 20:57 UTC, tznamena requested changes

2024-12-03 20:57 UTC, tznamena commented on test_check_dvcs.py
> +                ['ABC-0900', 'ABC-0900', 'ABC-0900'],
Would this case ever occur given that our regexp is `aap-[0-9]+`?

2024-12-03 20:57 UTC, tznamena commented on test_check_dvcs.py
> +    def test_bad_result(self, pr_title_jira, possible_commit_jiras, source_branch_jira, expected_in_message):
This test method is testing good and bad results, I would suggest we call it `test_decissions_output`.

2024-12-03 20:57 UTC, tznamena commented on test_check_dvcs.py
> +            "Validate AAP-1234 marker format",
Let's make the ids unique.

2024-12-03 20:57 UTC, tznamena commented on test_check_dvcs.py
> +    @pytest.mark.parametrize(
Since the array named `possible_commit_jiras` can only either be empty or contain either JIRA numbers matching regexp `aap-[0-9]+` or magic string `NO_JIRA`, this set of parameters does the same thing four times.
Let's roll it as a one set of parameters for the test below instead of having a whole test method.

2024-12-03 20:57 UTC, tznamena commented on test_check_dvcs.py
> +        [
Let's add a few more sets of parameters:
* testing `NO_JIRA` being in the middle of the text
* testing `NO_JIRA` being at the end
* and the same for an `AAP-1234` (using different number in each for ease of debugging).

2024-12-04 23:09 UTC, tznamena commented on test_check_dvcs.py
> +                ['ABC-0900', 'ABC-0900', 'ABC-0900'],
I don't see how was the previous comment addressed.

The function `make_decisions()` is called with array of Jira numbers from commits. The values do not match our regexp therefore we would never call the function with these parameters so I think we should drop this set of parameters.

2024-12-04 23:11 UTC, tznamena commented on test_check_dvcs.py
> +                ['AAP-5678', f"{check_dvcs._NO_JIRA_MARKER} no marker", 'AAP-5678'],
The second entry in the array should have been only `{check_dvcs._NO_JIRA_MARKER}`.

2024-12-04 23:15 UTC, tznamena commented on README.md
> +# Implementing in another Repo
Github actions are always added in another repository so I think we can simply change the section title to "Usage"
```suggestion
# Usage
```

2024-12-05 12:54 UTC, jay-steurer commented on test_check_dvcs.py
> +                ['AAP-5678', f"{check_dvcs._NO_JIRA_MARKER} no marker", 'AAP-5678'],
That change will result on failed test case, not a green one, since the JIRA number does not match NO_JIRA

2024-12-05 15:51 UTC, tznamena commented on test_check_dvcs.py
> +                ['AAP-5678', f"{check_dvcs._NO_JIRA_MARKER} no marker", 'AAP-5678'],
That would be correct behavior, if we see different Jira numbers or a mix of `AAP-5678` and `NO_JIRA` then the check should fail.

2024-12-05 16:00 UTC, jay-steurer commented on test_check_dvcs.py
> +                ['AAP-5678', f"{check_dvcs._NO_JIRA_MARKER} no marker", 'AAP-5678'],
OK, I will move this test out of the "happy path"

2024-12-05 16:01 UTC, jay-steurer commented on test_check_dvcs.py
> +                ['ABC-0900', 'ABC-0900', 'ABC-0900'],
ok. Updating

2024-12-05 16:16 UTC, tznamena approved these changes

2024-12-05 16:23 UTC, merged